### PR TITLE
add exception to account_get_addresses

### PR DESCRIPTION
**Pull request by AstroWa3l**
## Description
Just added JSON decode error exception that is used in other functions throughout library

## Where should the reviewer start?
file -> account.py 
function -> get_account_addresses 

## Motivation and context
Was breaking due to JSON Decode error

## Which issue it fixes?
Handles the JSON decode error as an exception 

## How has this been tested?
using the tests.py file

### CODE REVIEW

**Comment by AstroWa3l** [comment]
going to add more changes...

**Comment by QuixoteSystems** [comment]
Ok, perfect. But don't worry, you can send PR for just one thing. It is fine ;-)

**Comment by AstroWa3l** [comment]
Okay, I will haha we need to have the JSON decode exception in this function anyways... I will add more after I test more functions.

**Comment by QuixoteSystems** [comment]
Yeah, you are right. It is better manage that error always.

**Pull request merged**
